version: "3.9"

services:
  app:
    build:
      context: .
    image: saobot:latest
    container_name: sao_bot
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongodb:27017/SaoBot_Mongo_Db?authSource=admin

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/SaoBot_Pg_Db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=SaoBot_Mongo_Db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_DB=SaoBot_Pg_Db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  pg_data:
  redis-data:

networks:
  saonet:
    external: true